//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_Company.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdressSet
    {
        public AdressSet()
        {
            this.HouseSet = new HashSet<HouseSet>();
            this.ClientSet = new HashSet<ClientSet>();
        }
    
        public int AdressId { get; set; }
        public string Town { get; set; }
        public string Street { get; set; }
        public string HouseNumber { get; set; }
        public string ZipCode { get; set; }
    
        public virtual ICollection<HouseSet> HouseSet { get; set; }
        public virtual ICollection<ClientSet> ClientSet { get; set; }
    }
}
