//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_Company.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseSet
    {
        public int ObjectId { get; set; }
        public int Year { get; set; }
        public int Size { get; set; }
        public string Type { get; set; }
        public int Policy_PolicyId { get; set; }
        public int AdressSet_AdressId { get; set; }
    
        public virtual AdressSet AdressSet { get; set; }
        public virtual PolicySet PolicySet { get; set; }
    }
}
