//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_Company.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicySet
    {
        public PolicySet()
        {
            this.CarSet = new HashSet<CarSet>();
            this.HouseSet = new HashSet<HouseSet>();
        }
    
        public int PolicyId { get; set; }
        public int Duration { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string ObjectType { get; set; }
        public int ClientClientId { get; set; }
    
        public virtual ICollection<CarSet> CarSet { get; set; }
        public virtual ClientSet ClientSet { get; set; }
        public virtual ICollection<HouseSet> HouseSet { get; set; }
    }
}
